In [1]:
import numpy as np 
import pandas as pd
data=pd.read_csv("Data.csv", sep=';',on_bad_lines='skip')
print(data.head())

                                               Email      class
0  Salut ! Pouvez m'aider a ouvrir mon compte e_c...  Marketing
1                   Juste de créer un site web merci        web
2  Bonjour moi je me nomme Yazidou Je suis Nigïer...        web
3  Bonjour j'ai une ambition selon laquelle j'aim...        web
4                               Besoin d'un site web        web


In [2]:
data.shape

(60, 2)

In [3]:
print(data["class"].value_counts())

web           40
Marketing     17
 web           2
 Marketing     1
Name: class, dtype: int64


In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data["class_encoding"]=labelencoder.fit_transform(data["class"])
data.head()

Email      class  \
0  Salut ! Pouvez m'aider a ouvrir mon compte e_c...  Marketing   
1                   Juste de créer un site web merci        web   
2  Bonjour moi je me nomme Yazidou Je suis Nigïer...        web   
3  Bonjour j'ai une ambition selon laquelle j'aim...        web   
4                               Besoin d'un site web        web   

   class_encoding  
0               2  
1               3  
2               3  
3               3  
4               3

In [5]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud

In [6]:
#apply message lower case
messages=data["Email"].str.lower().apply(word_tokenize)
print(messages)

0     [salut, !, pouvez, m'aider, a, ouvrir, mon, co...
1              [juste, de, créer, un, site, web, merci]
2     [bonjour, moi, je, me, nomme, yazidou, je, sui...
3     [bonjour, j'ai, une, ambition, selon, laquelle...
4                             [besoin, d'un, site, web]
5     [je, veut, créer, gliseéglise, un, site, web, ...
6                [créer, gliseéglise, une, application]
7                [service, de, création, de, site, web]
8                [service, de, création, de, site, web]
9                [service, de, création, de, site, web]
10               [service, de, création, de, site, web]
11          [création, des, applications, ,, site, web]
12    [bonjour, ,, j'envie, de, créer, un, site, web...
13                         [création, une, application]
14               [service, de, création, de, site, web]
15                        [service, digital, marketing]
16               [service, de, création, de, site, web]
17               [service, de, création, de, sit

In [7]:
#messages remove stopwords
def remove_stop_words(messages):
    no_stop = []
    for message in messages:
        if message not in stopwords.words('french'):
            no_stop.append(message)
    return no_stop
messages=messages.apply(remove_stop_words)

In [8]:
print(messages)

0     [salut, !, pouvez, m'aider, a, ouvrir, compte,...
1                      [juste, créer, site, web, merci]
2     [bonjour, nomme, yazidou, nigïerien, ambition,...
3     [bonjour, j'ai, ambition, selon, laquelle, j'a...
4                             [besoin, d'un, site, web]
5     [veut, créer, gliseéglise, site, web, entrepri...
6                     [créer, gliseéglise, application]
7                        [service, création, site, web]
8                        [service, création, site, web]
9                        [service, création, site, web]
10                       [service, création, site, web]
11               [création, applications, ,, site, web]
12    [bonjour, ,, j'envie, créer, site, web, publie...
13                              [création, application]
14                       [service, création, site, web]
15                        [service, digital, marketing]
16                       [service, création, site, web]
17                       [service, création, sit

In [9]:
# Define a function to lemmatization
def lemmatize(messages):
    lemmatizer = WordNetLemmatizer()
    # Create the lemmatized list
    lemmatized = []
    for message in messages:
            # Lemmatize and append
            lemmatized.append(lemmatizer.lemmatize(message))
    return " ".join(lemmatized)

messages = messages.apply(lemmatize)
print(messages)

0     salut ! pouvez m'aider a ouvrir compte e_commerce
1                            juste créer site web merci
2     bonjour nomme yazidou nigïerien ambition desir...
3     bonjour j'ai ambition selon laquelle j'aimerai...
4                                  besoin d'un site web
5           veut créer gliseéglise site web entreprises
6                         créer gliseéglise application
7                             service création site web
8                             service création site web
9                             service création site web
10                            service création site web
11                      création application , site web
12    bonjour , j'envie créer site web publier docum...
13                                 création application
14                            service création site web
15                            service digital marketing
16                            service création site web
17                            service création s

In [10]:
data["new_Message"]=messages
display(data)

Email       class  \
0   Salut ! Pouvez m'aider a ouvrir mon compte e_c...   Marketing   
1                    Juste de créer un site web merci         web   
2   Bonjour moi je me nomme Yazidou Je suis Nigïer...         web   
3   Bonjour j'ai une ambition selon laquelle j'aim...         web   
4                                Besoin d'un site web         web   
5   Je veut créer gliseéglise un site web pour mon...         web   
6                   Créer gliseéglise une application         web   
7                     service de création de site web         web   
8                     service de création de site web         web   
9                     service de création de site web         web   
10                    service de création de site web         web   
11                 création des applications,site web         web   
12  Bonjour, j'envie de créer un site web pour pub...         web   
13                           création une application         web   
14                    service de création de site web         web   
15                          service digital marketing   Marketing   
16                    service de création de site web         web   
17                    service de création de site web         web   
18                    service de création de site web         web   
19                    service de création de site web         web   
20                                 service E-commerce   Marketing   
21      Servicecréation des applications web / mobile         web   
22  Demande d'espaces pour promotion de vente en l...   Marketing   
23                          Service Digital Marketing   Marketing   
24      Servicecréation des applications web / mobile         web   
25                            égliseLa vente en ligne   Marketing   
26                           Service Comerce en ligne   Marketing   
27  Je veux vendre mes produits en ligne et je ber...   Marketing   
28  créer un site internet ou des locations des ma...         web   
29                       demander aussi des marketing   Marketing   
30              créationéglised'une campagne digitale   Marketing   
31       Je veux une idéglisee sur le marketingéglise   Marketing   
32                                         e-commerce   Marketing   
33  je veux créer une application qui permet aux e...         web   
34                                           Site web         web   
35                                   Besoin d'un site         web   
36               projet commerce et la vente en ligne   Marketing   
37  Je voulais création un site web pour que les g...         web   
38   Veuillez m'aider église créer un site Web église         web   
39               Au peut faire le marketing avec vous   Marketing   
40                      création site internet église         web   
41                    J'arrive pas créer un site web          web   
42   Je veux créer un site des vidéos et des musiques         web   
43                         Je peux créer une Site web         web   
44  J'aimerais créer une site web pour la vente de...         web   
45  Je aimerais création mon entreprise commercial...         web   
46         Je souhaite héglisebergéglise mon site web         web   
47                            la création un site web         web   
48                    Je veux créer ma propre société         web   
49  Je voulais avoir un site web pour partager et ...         web   
50                           Pour vendre des produits   Marketing   
51                      J'aimerais créer un site Web          web   
52                     Web and mobile app development         web   
53                     Recherche creation du site web         web   
54      J'aimerais créer un site web pour la création         web   
55                            De ma boutique en ligne   Marketing   
56                                             Vendre   Marketing   
57                    Je veut aussi créer un s

In [11]:
#train-test-split
from sklearn.model_selection import train_test_split
X=data["new_Message"]
Y=data["class_encoding"]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [12]:
#Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(strip_accents='ascii')
tfidf_train = vectorizer.fit_transform(x_train)
tfidf_test = vectorizer.transform(x_test)

In [13]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [14]:
mNB=MultinomialNB()
mNB.fit(tfidf_train,y_train)
Y_pred = mNB.predict(tfidf_test)
print("Accuracy: "+str(accuracy_score(y_test, Y_pred)))
print('\n')
print(classification_report(y_test, Y_pred))
print('\n')
print(confusion_matrix(y_test, Y_pred))

Accuracy: 0.9166666666666666


              precision    recall  f1-score   support

           2       1.00      0.67      0.80         3
           3       0.90      1.00      0.95         9

    accuracy                           0.92        12
   macro avg       0.95      0.83      0.87        12
weighted avg       0.92      0.92      0.91        12



[[2 1]
 [0 9]]


In [20]:
#Make prediction
pred = mNB.predict(vectorizer.transform(["creer une application web"])) # Marketing => 2 & Web => 3
pred

array([3])

In [21]:
pred = mNB.predict(vectorizer.transform(["E-commerce en ligne"])) # Marketing => 2 & Web => 3
pred

array([2])